### source code to loading
source("D://R_code//R_exe//Setting//Setting_Packages.r")
suppressWarnings(source("D://R_code//R_exe//Setting//Setting_Version_phone.r"))
source("D://R_code//R_exe//Setting//Setting_KeyWord.r")
source("D://R_code//R_exe//Setting//Setting_TranslateFunction.r")
Sys.setlocale(category='LC_ALL', locale='C')
source("D://R_code//R_exe//Setting//Setting_Bad_KeyWord.r")
Sys.setlocale(category='LC_ALL', locale='')
suppressWarnings(source("D://R_code//R_exe//Setting//Setting_Version_phone_for_all.r"))
source("D://R_code//R_exe//Setting//Setting_UpdateTime.r")
source("D://R_code//R_exe//Setting//Setting_Spider.r")
